project:
  type: website

website:
  title: "ForMedStudents"
  page-footer: 
   left:
    info.formedstudents@gmail.com
   right:
       - text: "About"
         href: about.qmd
  navbar:
    left:
      - href: index.qmd
        text: Home
      - applications.qmd
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

