project:
  type: website

website:
  title: "ForMedStudents"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - applications.qmd
      - topics.qmd
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

