---
title: "5 MORE Helpful Resources for Years 1 and 2 of Med School"
author: "Hafeez Nathoo"
date: "2025-07-04"
categories: [ResourcesForMedStudents]
---

As a follow up to our [last article](https://formedstudents.netlify.app/applications/5_useful_resources/) we wanted to share 5 more resources that we've found useful through years 1 and 2 of medical school (preclerkship)

## Reminder - Why bother using anything outside lecture notes?

As you progress through medical school you will see much variation in didactic content, often delivered to you via powerpoint. While some lecturers strike a perfect balance - oftentimes there can be too much or too little detail, or a lack of clarity.

Over the last two years in medical school pre clerkship program we have come across several third party resources which have helped us fill in the gaps and explore content to a deeper level.

The below list is not in a rank order, as each resource has it pros and cons.

*Note, we are at a Canadian medical school - USMLE specific resources are not as emphasized*

## The List:

[AMBOSS](https://www.amboss.com/int)

-   **Pros:** - Extremely comprehensive with great visuals, a slick interface, and great practice questions. Very visually appealing with key information highlighted. Pretty much as close as I have gotten to an 'All in One' resource.

-   **Cons:** - The amazing quality comes with a cost, you will need a subscription.

-   **Use case:** For us, we used the library version only (not as many practice questions but much cheaper) and found it amazing to fill in gaps from lecture and to study, if you can afford it would recommend the version with more practice questions.

[The Stanford 25](https://www.ncbi.nlm.nih.gov/books/NBK430685/)

-   **Pros:** - A good resource to brush up on physical exam skills, which in years 1 and 2 are not as frequently used (in comparison to clinical rotations in y3 onward)

-   **Cons:** - Has high yield exams but not much info on connections to pathophsyiology.

-   **Use case:** For us, a good review to help connect findings for a given disease presented in lecture with the actual physical exam conducted, and a nice review before OSCEs.

[Peds Cases from the University of Alberta](https://www.pedscases.com/)

-   **Pros:** - Good resource with one pager summaries of many high yield topics in pediatrics.

-   **Cons:** - Good for reference and review, but the concise nature of the one pagers means you should probably learn the underlying topic in more detail (as needed) before using these.

-   **Use case:** Useful in case based learning and as summary documents to accompany lectures.

[Duke Suture Skills Course by Dr. Zenn](https://www.youtube.com/watch?v=TFwFMav_cpE&ab_channel=Dr.Zenn)

-   **Pros:** - A single video which covers many basic stitches, very practical for preclerkship medical students to get some exposure to suturing. Do note there are tons of videos out there, this is a personal favorite and was recommended to me by a resident.

-   **Cons:** - Learning when to use each stitch and doing this in practice is a different ball game, but for Y1/2 medical students this resource is good.

-   **Use case:** An efficient introduction to suturing which covers a lot of bases for first timers, though you will need to practice on your own with a kit at home to follow along.

### Thank you!

We hope you found this useful!
